const express = require('express')
const middleware = require('../middleware/middleware')

const buildingRoutes = require('./building-routes')
const roomRoutes = require('./room-routes')
const majoringRoutes = require('./majoring-routes')
const studyProgramRoutes = require('./study-program-routes')
const semesterRoutes = require('./semester-routes')
const batchRoutes = require('./batch-routes')
const lecturerRoutes = require('./lecturer-account-routes')
const coursesRoutes = require('./courses-routes')
const classScheduleRoutes = require('./class-schedule-routes')
const classRoutes = require('./class-routes')
const lecturesRoutes = require('./lectures-routes')
const studentAccountRoutes = require('./student-account-routes')
const adminAccountRoutes = require('./admin-account-routes')
const studentStatusRoutes = require('./student-status-routes')
const presenceRoutes = require('./presence-routes')
const uktRoutes = require('./ukt-routes')
const reResgitrationRoutes = require('./re-registration-routes')
const annoncementRoutes = require('./announcement-routes')
const questionnaireRoutes = require('./questionnaire-routes')
const graduationRoutes = require('./graduation-routes')
const internshipRoutes = require('./internship-routes')
const skillsRoutes = require('./skills-routes')
const achievementRoutes = require('./achievement-routes')
const orgRoutes = require('./organization-routes')
const ilRotes = require('./international-language-routes')
const parentsRoutes = require('./parents-routes')
const spRoutes = require('./student-profile-routes')
const vcRoutes = require('./value-courses-routes')
const authRoutes = require('./auth-routes')

const routes = app => {
  app.use('/uploads', express.static('../../public/uploads'))

  app.use('/buildings', middleware.authenticate, buildingRoutes)
  app.use('/rooms', middleware.authenticate, roomRoutes)
  app.use('/majorings', middleware.authenticate, majoringRoutes)
  app.use('/studyPrograms', middleware.authenticate, studyProgramRoutes)
  app.use('/semesters', middleware.authenticate, semesterRoutes)
  app.use('/batchs', middleware.authenticate, batchRoutes)
  app.use('/lecturerAccounts', middleware.authenticate, lecturerRoutes)
  app.use('/courses', middleware.authenticate, coursesRoutes)
  app.use('/classSchedules', middleware.authenticate, classScheduleRoutes)
  app.use('/classLectures', middleware.authenticate, classRoutes)
  app.use('/lectures', middleware.authenticate, lecturesRoutes)
  app.use('/studentAccounts', middleware.authenticate, studentAccountRoutes)
  app.use('/adminAccounts', middleware.authenticate, adminAccountRoutes)
  app.use('/studentStatus', middleware.authenticate, studentStatusRoutes)
  app.use('/presence', presenceRoutes)
  app.use('/ukt', middleware.authenticate, uktRoutes)
  app.use('/reRegistrations', middleware.authenticate, reResgitrationRoutes)
  app.use('/announcements', middleware.authenticate, annoncementRoutes)
  app.use('/questionnaire', middleware.authenticate, questionnaireRoutes)
  app.use('/graduations', middleware.authenticate, graduationRoutes)
  app.use('/internship', middleware.authenticate, internshipRoutes)
  app.use('/skills', middleware.authenticate, skillsRoutes)
  app.use('/achievement', middleware.authenticate, achievementRoutes)
  app.use('/organizations', middleware.authenticate, orgRoutes)
  app.use('/internationalLanguages', middleware.authenticate, ilRotes)
  app.use('/parents', middleware.authenticate, parentsRoutes)
  app.use('/studentProfile', middleware.authenticate, spRoutes)
  app.use('/valueCourses', middleware.authenticate, vcRoutes)
  app.use('/auth', authRoutes)
}

module.exports = routes